-- MySQL DDL generated from ERWin-like metadata
-- 운영 반영 전 실제 ERWin/DB 컬럼과 대조하세요.
SET NAMES utf8mb4;

DROP TABLE IF EXISTS TB_BOOK_PERF_MERCHANT;
CREATE TABLE TB_BOOK_PERF_MERCHANT (
  MERCHANT_ID VARCHAR(20) NOT NULL COMMENT '가맹점ID',
  MERCHANT_NM VARCHAR(100) NOT NULL COMMENT '가맹점명',
  BIZ_NO VARCHAR(10) NULL COMMENT '사업자번호',
  MCC_CD VARCHAR(4) NULL COMMENT 'MCC코드',
  APPLY_START_DT VARCHAR(8) NOT NULL COMMENT '적용시작일자',
  APPLY_END_DT VARCHAR(8) NULL COMMENT '적용종료일자',
  USE_YN CHAR(1) NOT NULL COMMENT '사용여부',
  REG_DTM DATETIME NOT NULL COMMENT '등록일시',
  UPD_DTM DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (MERCHANT_ID, APPLY_START_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='도서공연가맹점테이블';


DROP TABLE IF EXISTS TB_TRAD_MARKET_MERCHANT;
CREATE TABLE TB_TRAD_MARKET_MERCHANT (
  MERCHANT_ID VARCHAR(20) NOT NULL COMMENT '가맹점ID',
  MERCHANT_NM VARCHAR(100) NOT NULL COMMENT '가맹점명',
  MARKET_NM VARCHAR(100) NULL COMMENT '시장명',
  BIZ_NO VARCHAR(10) NULL COMMENT '사업자번호',
  APPLY_START_DT VARCHAR(8) NOT NULL COMMENT '적용시작일자',
  APPLY_END_DT VARCHAR(8) NULL COMMENT '적용종료일자',
  USE_YN CHAR(1) NOT NULL COMMENT '사용여부',
  REG_DTM DATETIME NOT NULL COMMENT '등록일시',
  UPD_DTM DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (MERCHANT_ID, APPLY_START_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='전통시장가맹점테이블';


DROP TABLE IF EXISTS TB_GENERAL_DEDUCT_MERCHANT;
CREATE TABLE TB_GENERAL_DEDUCT_MERCHANT (
  MERCHANT_ID VARCHAR(20) NOT NULL COMMENT '가맹점ID',
  MERCHANT_NM VARCHAR(100) NOT NULL COMMENT '가맹점명',
  BIZ_NO VARCHAR(10) NULL COMMENT '사업자번호',
  MCC_CD VARCHAR(4) NULL COMMENT 'MCC코드',
  APPLY_START_DT VARCHAR(8) NOT NULL COMMENT '적용시작일자',
  APPLY_END_DT VARCHAR(8) NULL COMMENT '적용종료일자',
  USE_YN CHAR(1) NOT NULL COMMENT '사용여부',
  REG_DTM DATETIME NOT NULL COMMENT '등록일시',
  UPD_DTM DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (MERCHANT_ID, APPLY_START_DT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='소득공제가맹점테이블';


DROP TABLE IF EXISTS TB_CARD_SALES_LEDGER;
CREATE TABLE TB_CARD_SALES_LEDGER (
  SALES_SEQ_NO VARCHAR(30) NOT NULL COMMENT '매출일련번호',
  SALES_DT VARCHAR(8) NOT NULL COMMENT '매출일자',
  SALES_TM VARCHAR(6) NULL COMMENT '매출시간',
  CARD_NO VARCHAR(20) NOT NULL COMMENT '카드번호',
  CUSTOMER_ID VARCHAR(20) NOT NULL COMMENT '고객ID',
  MERCHANT_ID VARCHAR(20) NOT NULL COMMENT '가맹점ID',
  APPROVAL_NO VARCHAR(20) NULL COMMENT '승인번호',
  SALES_AMT DECIMAL(15,0) NOT NULL COMMENT '매출금액',
  VAT_AMT DECIMAL(15,0) NULL COMMENT '부가세금액',
  SERVICE_FEE DECIMAL(15,0) NULL COMMENT '봉사료',
  INSTALLMENT_MONTH DECIMAL(2,0) NULL COMMENT '할부개월수',
  CANCEL_YN CHAR(1) NOT NULL COMMENT '취소여부',
  SALES_STATUS_CD VARCHAR(2) NOT NULL COMMENT '매출상태코드',
  MCC_CD VARCHAR(4) NULL COMMENT '업종코드',
  ORG_FILE_NM VARCHAR(100) NULL COMMENT '원천파일명',
  BASE_YM VARCHAR(6) NOT NULL COMMENT '기준년월',
  REG_DTM DATETIME NOT NULL COMMENT '등록일시',
  UPD_DTM DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (SALES_SEQ_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='매출원장테이블';

CREATE INDEX IDX_CARD_SALES_LEDGER_01 ON TB_CARD_SALES_LEDGER (SALES_DT);
CREATE INDEX IDX_CARD_SALES_LEDGER_02 ON TB_CARD_SALES_LEDGER (MERCHANT_ID);
CREATE INDEX IDX_CARD_SALES_LEDGER_03 ON TB_CARD_SALES_LEDGER (CUSTOMER_ID);

DROP TABLE IF EXISTS TB_DEDUCTION_MONTHLY_SUMMARY;
CREATE TABLE TB_DEDUCTION_MONTHLY_SUMMARY (
  BASE_YM VARCHAR(6) NOT NULL COMMENT '기준년월',
  CUSTOMER_ID VARCHAR(20) NOT NULL COMMENT '고객ID',
  DEDUCT_TYPE_CD VARCHAR(2) NOT NULL COMMENT '공제유형코드',
  DEDUCT_TYPE_NM VARCHAR(50) NOT NULL COMMENT '공제유형명',
  TXN_COUNT DECIMAL(15,0) NOT NULL COMMENT '거래건수',
  SALES_AMT DECIMAL(15,0) NOT NULL COMMENT '매출금액',
  DEDUCT_AMT DECIMAL(15,0) NOT NULL COMMENT '공제대상금액',
  REG_DTM DATETIME NOT NULL COMMENT '등록일시',
  UPD_DTM DATETIME NULL COMMENT '수정일시',
  PRIMARY KEY (BASE_YM, CUSTOMER_ID, DEDUCT_TYPE_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='소득공제월별집계테이블';

CREATE INDEX IDX_DEDUCT_SUMMARY_01 ON TB_DEDUCTION_MONTHLY_SUMMARY (CUSTOMER_ID);
CREATE INDEX IDX_DEDUCT_SUMMARY_02 ON TB_DEDUCTION_MONTHLY_SUMMARY (BASE_YM);

DROP TABLE IF EXISTS TB_BATCH_RUN_LOG;
CREATE TABLE TB_BATCH_RUN_LOG (
  RUN_ID VARCHAR(36) NOT NULL COMMENT '실행ID',
  BATCH_ID VARCHAR(80) NOT NULL COMMENT '배치ID',
  BASE_YM VARCHAR(6) NOT NULL COMMENT '기준년월',
  STATUS_CD VARCHAR(20) NOT NULL COMMENT '상태코드',
  START_DTM DATETIME NOT NULL COMMENT '시작일시',
  END_DTM DATETIME NULL COMMENT '종료일시',
  SOURCE_COUNT DECIMAL(15,0) NULL COMMENT '원천건수',
  EXCLUDED_COUNT DECIMAL(15,0) NULL COMMENT '제외건수',
  TARGET_COUNT DECIMAL(15,0) NULL COMMENT '대상건수',
  ERROR_MESSAGE VARCHAR(1000) NULL COMMENT '오류메시지',
  PRIMARY KEY (RUN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='배치실행로그테이블';


DROP TABLE IF EXISTS TB_DEDUCTION_ERROR_TXN;
CREATE TABLE TB_DEDUCTION_ERROR_TXN (
  RUN_ID VARCHAR(36) NOT NULL COMMENT '실행ID',
  SALES_SEQ_NO VARCHAR(30) NOT NULL COMMENT '매출일련번호',
  BASE_YM VARCHAR(6) NOT NULL COMMENT '기준년월',
  CUSTOMER_ID VARCHAR(20) NOT NULL COMMENT '고객ID',
  MERCHANT_ID VARCHAR(20) NOT NULL COMMENT '가맹점ID',
  SALES_AMT DECIMAL(15,0) NOT NULL COMMENT '매출금액',
  ERROR_CD VARCHAR(30) NOT NULL COMMENT '오류코드',
  ERROR_MSG VARCHAR(300) NOT NULL COMMENT '오류메시지',
  REG_DTM DATETIME NOT NULL COMMENT '등록일시',
  PRIMARY KEY (RUN_ID, SALES_SEQ_NO, ERROR_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='소득공제오류거래테이블';

CREATE INDEX IDX_DEDUCT_ERROR_01 ON TB_DEDUCTION_ERROR_TXN (BASE_YM, ERROR_CD);


DROP TABLE IF EXISTS TB_DEDUCTION_MONTHLY_SUMMARY;

CREATE TABLE TB_DEDUCTION_MONTHLY_SUMMARY (
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    BASE_YM VARCHAR(6) NOT NULL,
    MERCHANT_TYPE VARCHAR(30) NOT NULL,
    TOTAL_AMT DECIMAL(15,0) NOT NULL,
    TXN_COUNT INT NOT NULL,
    REG_DTM DATETIME NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, BASE_YM, MERCHANT_TYPE)
);