DROP TABLE IF EXISTS TB_DEDUCTION_MONTHLY_SUMMARY;

CREATE TABLE TB_DEDUCTION_MONTHLY_SUMMARY (
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    BASE_YM VARCHAR(6) NOT NULL,
    MERCHANT_TYPE VARCHAR(30) NOT NULL,
    TOTAL_AMT DECIMAL(15,0) NOT NULL,
    TXN_COUNT INT NOT NULL,
    REG_DTM DATETIME NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, BASE_YM, MERCHANT_TYPE),
    INDEX IDX_DEDUCTION_MONTHLY_SUMMARY_01 (BASE_YM),
    INDEX IDX_DEDUCTION_MONTHLY_SUMMARY_02 (CUSTOMER_ID)
);
